M  scripts/mnm

diff --git a/scripts/mnm b/scripts/mnm
--- a/scripts/mnm
+++ b/scripts/mnm
@@ -4,97 +4,94 @@
 
 config_path="$HOME/.config/mnm/mnm.conf"
 
-# create config if it doesn't exist and read it. Create directories if they don't exist.
+# Read config
 #
-create_config() {
-    mkdir -p ~/.config/mnm 2>/dev/null ; touch "$config_path" 2>/dev/null
-    printf "path=~/notes\ndirectories=%s" "\"notes daily\"" > "$config_path" 
-    echo "Config file created at $config_path"
-}
-
 read_config() {
-    # shellcheck source=../mnm/mnm.conf
-    . "$config_path" 
+  # shellcheck source=../mnm/mnm.conf
+  . "$config_path"
 }
 
-if [ -f "$config_path" ]; then read_config; else create_config; read_config; fi
+if [ -f "$config_path" ]; then
+  read_config
+else
+  echo "Config file not found"
+  exit 1
+fi
 
 for directory in $directories; do
-    [ -d "$path/$directory" ] || mkdir -p "$path/$directory" 2>/dev/null
+  [ -d "$path/$directory" ] || mkdir -p "$path/$directory" 2>/dev/null
 done
 
 # Hep text
 #
 help() {
-    echo "usage: n [-h] [-c]"
-    echo "  -h      display help"
-    echo "  -c      create note to a selected folder"
-    echo "  -s      search all notes, and open selected one"
-    echo "  -d      search notes in directory, and open selected one"
-    exit 1
+  echo "usage: n [-h] [-c]"
+  echo "  -h      display help"
+  echo "  -c      create note to a selected folder"
+  echo "  -s      search all notes, and open selected one"
+  echo "  -d      search notes in directory, and open selected one"
+  exit 1
 }
 
 # Create note
 #
-get_note_file_name() {
-    echo "$(date +%Y%m%d)_$(echo "$1" | tr '[:upper:]' '[:lower:]' | tr ' ' '_' | tr -d '\n').md"
-}
-
-create_markdown_file() {
-    touch "$1"
-    {
-        echo "---"
-        echo "date: $(date +%Y-%m-%d)"
-        echo "---"
-        printf "\n"
-        echo "# $(echo "$2" | sed 's/.*/\L&/; s/[a-z]*/\u&/g')"
-        printf "\n"
-    } > "$1"
+open_markdown_file() {
+  mkdir -p "$1"
+  file_path="$1"/README.md
+  {
+    echo "---"
+    echo "date: $(date "+%Y-%m-%d %H:%M:%S")"
+    echo "tags: "
+    echo "---"
+    printf "\n"
+    echo "# "
+  } >"$file_path"
+  $EDITOR "$file_path"
 }
 
 create_note() {
-    directory=$(echo "$directories" | tr " " "\n" | fzf)
-    echo "Enter note name: "
-    read -r name
-    filename=$(get_note_file_name "$name")
-    filepath="$path/$directory/$filename"
-    [ ! -f "$filepath" ] && create_markdown_file "$filepath" "$name"
-    $EDITOR "$filepath"
+  directory=$(echo "$directories" | tr " " "\n" | fzf)
+  if [ $? -eq 130 ]; then
+    exit 0
+  fi
+  note_directory_name=$(date +%Y%m%d%H%M%S)
+  note_path="$path/$directory/$note_directory_name"
+  [ ! -f "$note_path" ] && open_markdown_file "$note_path"
 }
 
 # Search all notes or in directory
 #
 search_in_path() {
-    found_file_path=$(rg '' "$1" | fzf --delimiter=/ --with-nth -1 | cut -d":" -f1;)
-    [ -z "$found_file_path" ] && exit 1
-    $EDITOR "$found_file_path"
+  found_file_path=$(rg '' "$1" | fzf --delimiter=/ --with-nth -1 | cut -d":" -f1)
+  [ -z "$found_file_path" ] && exit 1
+  $EDITOR "$found_file_path"
 }
 
 search_note() {
-    search_in_path "$path"
+  search_in_path "$path"
 }
 
 search_directory() {
-    directory=$(echo "$directories" | tr " " "\n" | fzf)
-    search_in_path "$path/$directory"
+  directory=$(echo "$directories" | tr " " "\n" | fzf)
+  search_in_path "$path/$directory"
 }
 
 case $1 in
-    -h)
-        help
-        ;;
-    -c)
-        create_note
-        ;;
-    -s)
-        search_note
-        ;;
-    -d)
-        search_directory
-        ;;
-    *)
-        help
-        ;;
+  -h)
+    help
+    ;;
+  -c)
+    create_note
+    ;;
+  -s)
+    search_note
+    ;;
+  -d)
+    search_directory
+    ;;
+  *)
+    create_note
+    ;;
 esac
 
 exit 0
